In [1]:
#Using sklearn to  load California housing Datasets
from sklearn.datasets import fetch_california_housing
data1 = fetch_california_housing() #the dataset includes data, target, feature_names ,
#import pandas
import pandas as pd
#convert the data into pandas dataframa
df = pd.DataFrame(data=data1.data, columns =data1.feature_names )
df['MedianHousevalue'] = data1.target
print(df.head())
print(df.shape)
print(df.describe()) #get descriptive statistics



   MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3  5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4  3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   

   Longitude  MedianHousevalue  
0    -122.23             4.526  
1    -122.22             3.585  
2    -122.24             3.521  
3    -122.25             3.413  
4    -122.25             3.422  
(20640, 9)
             MedInc      HouseAge      AveRooms     AveBedrms    Population  \
count  20640.000000  20640.000000  20640.000000  20640.000000  20640.000000   
mean       3.870671     28.639486      5.429000      1.096675   1425.476744   
std        1.899822     12.585558      2.474173      0.473911   1132.462122   
min        0.49990

medinc: This the median income for household with a block (scaled and capped at 15 for higher income earners and 0.5 for lower median incomes)
HouseAge: The median house age within a block
AveRooms: This is the average number of rooms in the houses within a block
AveBedrms: This is the average number of bedrooms in the houses within a block
population: this is the total population within a block
AveOccup: average house occupancy. computed as the total population within a block divided by the number of households
Latitude and Longitude: These are the geographic coordinates of the block groups
MedianHouseValue:  Median house value for households within a block (measure in 10,000s

In [2]:
#check for null values
print(df.isnull().sum())
#import numpy
import numpy as np
A = np.array([[9,8,7], [6,6,7], [9,10,12]])
#find the inverse of B
B = np.array([[1,2,3], [5,6,4], [8,9,11]])
C = A + B
print(C)
F = np.linalg.inv(B)
print(F)
#finding pseudo inverse can be applied to any matrix even if it is not invertible
fp = np.linalg.pinv(B)
print(fp)

E = A * B
print(E)

D = A -B
print(D)

print("Tranposing matrix B",  np.transpose(B))

print("Transpose of A", A.T)

MedInc              0
HouseAge            0
AveRooms            0
AveBedrms           0
Population          0
AveOccup            0
Latitude            0
Longitude           0
MedianHousevalue    0
dtype: int64
[[10 10 10]
 [11 12 11]
 [17 19 23]]
[[-1.2  -0.2   0.4 ]
 [ 0.92  0.52 -0.44]
 [ 0.12 -0.28  0.16]]
[[-1.2  -0.2   0.4 ]
 [ 0.92  0.52 -0.44]
 [ 0.12 -0.28  0.16]]
[[  9  16  21]
 [ 30  36  28]
 [ 72  90 132]]
[[8 6 4]
 [1 0 3]
 [1 1 1]]
Tranposing matrix B [[ 1  5  8]
 [ 2  6  9]
 [ 3  4 11]]
Transpose of A [[ 9  6  9]
 [ 8  6 10]
 [ 7  7 12]]


In [3]:
#simulating preprocessing with slices
feature_1 = np.array([[123], [671],[781]])
feature_2 = np.array([[321],[654], [987]])
#combine two features into one
data_feature = np.hstack((feature_1, feature_2))
print(data_feature)
#normalize the data
normalized_data = data_feature/np.linalg.norm(data_feature)
print(normalized_data)

#normalization with Min-max Normalization to get a range between 0 and 1
normalized_date_minmax = (data_feature - np.min(data_feature))/(np.max(data_feature)- np.min(data_feature))
print(normalized_date_minmax)

#simulate the weights of features
weights = np.array([0.4, 0.6])

#calculate the weighted sum of the feature
weighted_sum = np.dot(data_feature, weights)
print(weighted_sum)

[[123 321]
 [671 654]
 [781 987]]
[[0.07657264 0.19983592]
 [0.41772555 0.40714234]
 [0.48620515 0.61444876]]
[[0.         0.22916667]
 [0.63425926 0.61458333]
 [0.76157407 1.        ]]
[241.8 660.8 904.6]
